### ISSUE TITLE
Query regarding multiple states. 

### ISSUE THREAD

**Issue by rajatsingla** [melodysdreamj/june#7]
Hi, If i want to use multiple states in a widget, how to do that? is that possible somehow?

something like:

```dart
JuneBuilder(
            () => CounterVM(),
            () => CounterVM2(),
            builder: (vm, vm2) =>  Text(
                  '${vm.count} ${vm2.count}',
            ),
)

class CounterVM extends JuneState {
  int count = 0;
}

class CounterVM2 extends JuneState {
  int count = 0;
}
```

**Comment by CodingWill0** [comment]
You can simply nest a JuneBuilder inside a JuneBuilder, I don't think there's any issue with that. But would like to see an official method, it is a relevant miss in the docs.

**Comment by melodysdreamj** [comment]
@CodingWill0, you're absolutely right! Nesting JuneBuilders is indeed the intended approach for using multiple states within a widget. I appreciate you pointing that out, and we will consider adding more details to the documentation to clarify this. Thanks for your feedback!
